from openmdp.MarkovDecisionProcess import MarkovDecisionProcess
from openmdp.PartiallyObservableMarkovDecisionProcess import PartiallyObservableMarkovDecisionProcess

MDP = MarkovDecisionProcess
POMDP = PartiallyObservableMarkovDecisionProcess
